apiVersion: 1

datasources:
  - name: Crypto Postgres
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: postgres:5432
    user: grafana
    secureJsonData:
      password: secret
    jsonData:
      database: crypto
      sslmode: disable